### ISSUE TITLE
kubectl astrads monitoring -n netapp-monitoring -r [YOUR REGISTRY] setup

### ISSUE THREAD

**Issue by hayatokurahashi** [NetAppDocs/astra-data-store#49]
Page: [Install Astra Data Store preview](https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads.html)

I think this should be "-m" to specify namespace.

root@hk-k8s3-m:~/manifests# kubectl astrads monitoring setup -n netapp-monitoring -r 10.216.43.195:5000
error fetching cluster no clusters found
root@hk-k8s3-m:~/manifests# kubectl astrads monitoring setup -m astrads-system  -r 10.216.43.195:5000
root@hk-k8s3-m:~/manifests#

root@hk-k8s3-m:~/manifests# kubectl astrads monitoring setup --help
Set up monitoring config for ADS Cluster

Usage:
  astrads monitoring setup [flags]

Flags:
  -h, --help                         help for setup
  **-m, --monitoringNamespace string   Specify monitoring namespace of monitoring operator (default "netapp-monitoring")**
  -r, --repo string                  Specify repo to fetch images for monitoring operator (default "docker.repo.eng.netapp.com/global/astra")

**Comment by netapp-dbagwell** [comment]
Thanks @hayatokurahashi for the catch. Will post here again when docs are updated.

**Comment by hayatokurahashi** [comment]
Great. thanks !

**Comment by netapp-mwallis** [comment]
Hi @hayatokurahashi, the documentation has been updated: https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads.html
The topic now states the requirement of "Before setting up monitoring, you will need an active Astra Data Store cluster in the astrads-system namespace", so that the commands will work as intended.

Thanks,
Michael
